import type { Metadata } from "next";
import { JetBrains_Mono, Geologica } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.css";
import SmoothScrollWrapper from "@/components/wrappers/smooth-scroll-wrapper";
import Navbar from "../components/layout/navbar/index";
import Footer from "@/components/layout/footer";

const JetBrains = JetBrains_Mono({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

const Geologicas = Geologica({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-geologica",
  display: "swap",
});

const googleSansCode = localFont({
  src: [
    {
      path: "./../../public/fonts/GoogleSansCode-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/fonts/GoogleSansCode-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../public/fonts/GoogleSansCode-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-google-sans-code",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${JetBrains.variable} ${Geologicas.variable} ${googleSansCode.variable} antialiased bg-black`}
      >
        <Navbar />
        <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
        <Footer />
      </body>
    </html>
  );
}
